export const productConstants={
    GET_PRODUCT_SECCESS:"SIGNUP_SECCESS",
    GET_PRODUCT_FAILURE:"SIGNUP_FAILURE",
    ADD_PRODUCT_SECCESS:"ADD_PRODUCT_SECCESS",
    DELETE_PRODUCT_SECCESS:"DELETE_PRODUCT_SECCESS",
    EDIT_PRODUCT_SECCESS:"EDIT_PRODUCT_SECCESS"

}